app:
  name: tg-agent
  log_level: INFO

storage:
  sqlite_path: data/agent.db

bot:
  echo_enabled: true
  reply_in_groups: false

chats:
  - chat_id: -1001802670428      
    alias: tatneft_zapad_escalation
  - chat_id: -1234567890
    alias: second_escalation
  - chat_id: -5275351843
    alias: test_group_chat

users:
  - user_id: 309881753
    role: service_coordinator
    name: 'Роберт П.'

  - user_id: 122976389
    role: bank
    name: 'Капитонов Денис'

  - user_id: 5130919462
    role: bank
    name: 'Арысланов Айрат'

  - user_id: 5797216921
    role: client
    name: 'Руслан Уцумиев'

  - user_id: 51084916065
    role: client
    name: 'Эльмира'


# управление ответами (репликами с уточняющей информацией по направленным эскалациям)

reply:
  enabled: true                  # главный рубильник: отвечать/не отвечать
  mode: reply                    # engineer_chat | reply
  engineer_chat_id: null         # если mode=engineer_chat — сюда шлём (chat_id)

  require_entities:
    - tid            # без TID не отвечаем

  allowed_roles:                 # роли, которые могут триггерить ответ бота
    - bank
    - service_coordinator
    - service_support
    - client

  include_entities:              # что выводить инженерам
    - azs
    - workplace
    - tid
    - ip
